[package]
name = "phlash-css"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.69"
ext-php-rs = { version = "0.10", features = ["anyhow"]}
lightningcss = "1.0.0-alpha.39"

[profile.release]
strip = "debuginfo"
